version: 43.0.9
pageUuid: ac8369ec-7cae-11ed-8b93-770ba1331c59
appTemplate:
  plugins:
    ordered:
      - query1:
          pluginTemplate:
            id: query1
            type: datasource
            subtype: RESTQuery
            resourceName: 509115aa-35ba-4369-b44a-c9a54deac8d6
            resourceDisplayName: '[sample] restapi'
            template:
              ordered:
                - queryRefreshTime: ''
                - paginationLimit: ''
                - body: ''
                - lastReceivedFromResourceAt: null
                - queryDisabledMessage: ''
                - servedFromCache: false
                - successMessage: ''
                - queryDisabled: ''
                - playgroundQuerySaveId: latest
                - resourceNameOverride: ''
                - runWhenModelUpdates: true
                - paginationPaginationField: ''
                - headers: ''
                - showFailureToaster: true
                - paginationEnabled: false
                - query: ''
                - playgroundQueryUuid: ''
                - playgroundQueryId: null
                - error: null
                - privateParams: []
                - runWhenPageLoadsDelay: ''
                - data: null
                - importedQueryInputs:
                    ordered: []
                - isImported: false
                - showSuccessToaster: true
                - cacheKeyTtl: ''
                - requestSentTimestamp: null
                - cookies: ''
                - metadata: null
                - queryRunTime: null
                - changesetObject: ''
                - errorTransformer: >-
                    // The variable 'data' allows you to reference the request's
                    data in the transformer. 

                    // example: return data.find(element => element.isError)

                    return data.error
                - finished: null
                - confirmationMessage: null
                - isFetching: false
                - changeset: ''
                - rawData: null
                - queryTriggerDelay: '0'
                - resourceTypeOverride: null
                - watchedParams: []
                - enableErrorTransformer: false
                - showLatestVersionUpdatedWarning: false
                - paginationDataField: ''
                - timestamp: 0
                - importedQueryDefaults:
                    ordered: []
                - enableTransformer: false
                - showUpdateSetValueDynamicallyToggle: true
                - runWhenPageLoads: false
                - transformer: >-
                    // type your code here

                    // example: return formatDataAsArray(data).filter(row =>
                    row.quantity > 20)

                    return data
                - events: []
                - queryTimeout: '10001'
                - requireConfirmation: false
                - type: GET
                - queryFailureConditions: ''
                - changesetIsObject: false
                - enableCaching: false
                - allowedGroups: []
                - bodyType: json
                - offlineQueryType: None
                - queryThrottleTime: '750'
                - updateSetValueDynamically: false
                - notificationDuration: ''
            createdAt: 2022-12-15T19:28:37.866Z
      - $main:
          pluginTemplate:
            id: $main
            type: frame
            subtype: Frame
            template:
              ordered:
                - type: main
                - sticky: false
                - isHiddenOnDesktop: false
                - isHiddenOnMobile: false
            style:
              ordered: []
            createdAt: 2022-12-15T19:28:48.432Z
      - text1:
          pluginTemplate:
            id: text1
            type: widget
            subtype: TextWidget2
            template:
              ordered:
                - heightType: auto
                - horizontalAlign: left
                - hidden: false
                - imageWidth: fit
                - showInEditor: false
                - verticalAlign: center
                - tooltipText: ''
                - value: 👋 **Hello {{ current_user.firstName || 'friend' }}!**
                - style:
                    ordered:
                      - color: info
                - disableMarkdown: false
                - overflowType: scroll
                - maintainSpaceWhenHidden: false
            style:
              ordered: []
            position2:
              position2:
                row: 1.2000000000000002
                height: 0.6
                width: 3
            createdAt: 2022-12-15T19:28:52.772Z
      - table1:
          pluginTemplate:
            id: table1
            type: widget
            subtype: TableWidget
            template:
              ordered:
                - showCustomButton: false
                - sortMappedValue:
                    ordered: []
                - _filteredSortedRenderedDataWithTypes: null
                - heightType: fixed
                - normalizedData: null
                - rowHeight: standard
                - saveChangesDisabled: ''
                - columnTypeProperties:
                    ordered: []
                - columnWidths: []
                - showSummaryFooter: false
                - disableRowSelectInteraction: false
                - columnWidthsMobile: []
                - hasNextAfterCursor: ''
                - columnTypeSpecificExtras:
                    ordered: []
                - onRowAdded: ''
                - columnHeaderNames:
                    ordered: []
                - alwaysShowPaginator: false
                - columnColors:
                    ordered: []
                - columnFrozenAlignments:
                    ordered: []
                - allowMultiRowSelect: false
                - columnFormats:
                    ordered: []
                - columnRestrictedEditing:
                    ordered: []
                - showFilterButton: true
                - _columnVisibility:
                    ordered: []
                - _columnSummaryTypes:
                    ordered: []
                - _columnsWithLegacyBackgroundColor:
                    set: []
                - showAddRowButton: false
                - _unfilteredSelectedIndex: null
                - nextBeforeCursor: ''
                - columnVisibility:
                    ordered: []
                - selectedPageIndex: '0'
                - applyDynamicSettingsToColumnOrder: true
                - rowColor:
                    array: []
                - actionButtonColumnName: Actions
                - resetAfterSave: true
                - filterStackType: and
                - downloadRawData: false
                - showFetchingIndicator: true
                - serverPaginated: false
                - data: '{{ query1.data.metadata.headers }}'
                - displayedData: null
                - actionButtons: []
                - actionButtonSelectsRow: true
                - selectRowByDefault: true
                - defaultSortByColumn: ''
                - paginationOffset: 0
                - columnAlignment:
                    ordered: []
                - columnSummaries:
                    object: {}
                - showBoxShadow: false
                - sortedDesc: false
                - customButtonName: ''
                - columnMappersRenderAsHTML:
                    ordered: []
                - showRefreshButton: true
                - pageSize: '20'
                - useDynamicColumnSettings: false
                - actionButtonPosition: left
                - dynamicRowHeights: false
                - bulkUpdateAction: ''
                - afterCursor: ''
                - onCustomButtonPressQueryName: ''
                - changeSet:
                    object: {}
                - sortedColumn: ''
                - _columnSummaryValues:
                    ordered: []
                - checkboxRowSelect: true
                - _compatibilityMode: false
                - showColumnBorders: false
                - clearSelectionLabel: Clear selection
                - _renderedDataWithTypes: null
                - columnAllowOverflow:
                    ordered: []
                - beforeCursor: ''
                - serverPaginationType: limitOffsetBased
                - onRowSelect: ''
                - showDownloadButton: true
                - selectedIndex: null
                - defaultSortDescending: false
                - _sortedDisplayedDataIndices: null
                - dynamicColumnSettings: null
                - totalRowCount: ''
                - recordUpdates:
                    array: []
                - newRow: null
                - emptyMessage: No rows found
                - columnEditable:
                    ordered: []
                - _viewerColumnSummaryTypes:
                    object: {}
                - filters:
                    array: []
                - displayedDataIndices: null
                - disableSorting:
                    ordered: []
                - columnMappers:
                    ordered: []
                - showClearSelection: false
                - doubleClickToEdit: true
                - overflowType: pagination
                - _reverseSortedDisplayedDataIndices: null
                - showTableBorder: true
                - selectedCell:
                    object:
                      index: null
                      data: null
                      columnName: null
                - columns: []
                - defaultSelectedRow: first
                - freezeActionButtonColumns: false
                - sort: null
                - _columns: []
                - sortByRawValue:
                    ordered: []
                - calculatedColumns: []
                - selectedRow:
                    object:
                      index: null
                      data: null
                - showPaginationOnTop: false
                - _reverseDisplayedDataIndices: null
                - nextAfterCursor: ''
                - useCompactMode: false
            style:
              ordered: []
            position2:
              position2:
                row: 2.1999999999999997
                height: 8
                width: 8
            createdAt: 2022-12-15T19:28:56.693Z
      - button1:
          pluginTemplate:
            id: button1
            type: widget
            subtype: ButtonWidget2
            template:
              ordered:
                - horizontalAlign: stretch
                - clickable: false
                - iconAfter: ''
                - submitTargetId: null
                - hidden: false
                - text: Button
                - showInEditor: false
                - tooltipText: ''
                - style:
                    ordered:
                      - border: danger
                      - background: highlight
                - styleVariant: solid
                - submit: false
                - iconBefore: ''
                - events:
                    ordered: []
                - loading: false
                - loaderPosition: auto
                - disabled: false
                - maintainSpaceWhenHidden: false
            style:
              ordered: []
            position2:
              position2:
                row: 8.6
                col: 8
                height: 1
                width: 3
            createdAt: 2022-12-15T19:29:02.007Z
      - textInput1:
          pluginTemplate:
            id: textInput1
            type: widget
            subtype: TextInputWidget2
            template:
              ordered:
                - spellCheck: false
                - readOnly: false
                - iconAfter: ''
                - showCharacterCount: false
                - autoComplete: false
                - maxLength: null
                - hidden: false
                - customValidation: ''
                - patternType: ''
                - hideValidationMessage: false
                - textBefore: ''
                - validationMessage: ''
                - textAfter: ''
                - showInEditor: false
                - showClear: false
                - pattern: ''
                - tooltipText: ''
                - labelAlign: left
                - formDataKey: '{{ self.id }}'
                - value: ''
                - style:
                    ordered:
                      - background: highlight
                - labelCaption: ''
                - labelWidth: '33'
                - autoFill: ''
                - placeholder: Enter value
                - label: Label
                - _validate: false
                - labelWidthUnit: '%'
                - invalid: false
                - iconBefore: ''
                - minLength: null
                - inputTooltip: ''
                - events:
                    ordered: []
                - autoCapitalize: none
                - loading: false
                - disabled: false
                - labelPosition: left
                - labelWrap: false
                - maintainSpaceWhenHidden: false
                - required: false
            style:
              ordered: []
            position2:
              position2:
                row: 1.2000000000000002
                col: 4
                height: 1
                width: 4
            createdAt: 2022-12-15T19:29:07.974Z
      - navigation1:
          pluginTemplate:
            id: navigation1
            type: widget
            subtype: NavigationWidget2
            template:
              ordered:
                - _disabledByIndex:
                    - ''
                    - ''
                    - ''
                - heightType: auto
                - iconByIndex:
                    array: []
                - srcWidth: null
                - _iconByIndex:
                    - ''
                    - ''
                    - ''
                - src: ''
                - overflowMode: scroll
                - _parentKeyByIndex:
                    - ''
                    - ''
                    - ''
                - _highlightByIndex:
                    - ''
                    - ''
                    - ''
                - parentKeyByIndex:
                    array: []
                - highlightByIndex:
                    array: []
                - _appTargetByIndex:
                    - ''
                    - ''
                    - ''
                - appTargetByIndex:
                    array: []
                - hidden: false
                - data:
                    array: []
                - srcHeight: null
                - itemTypeByIndex:
                    array: []
                - showInEditor: false
                - _itemTypeByIndex:
                    - app
                    - ''
                    - ''
                - orientation: horizontal
                - tooltipText: ''
                - style:
                    ordered:
                      - highlightText: rgba(48, 53, 56, 1)
                      - color: success
                - hiddenByIndex:
                    array: []
                - _hiddenByIndex:
                    - ''
                    - ''
                    - ''
                - storageBlobId: ''
                - _captionByIndex:
                    - ''
                    - ''
                    - ''
                - _hasMigratedNestedItems: true
                - captionByIndex:
                    array: []
                - altText: ''
                - itemMode: static
                - dbBlobId: ''
                - _tooltipByIndex:
                    - ''
                    - ''
                    - ''
                - _automaticallyHighlightedIndices:
                    array: []
                - tooltipByIndex:
                    array: []
                - events:
                    ordered: []
                - _ids:
                    - 2f355
                    - 80c87
                    - '20593'
                - iconPositionByIndex:
                    array: []
                - _iconPositionByIndex:
                    - ''
                    - ''
                    - ''
                - _keyByIndex:
                    - ''
                    - ''
                    - ''
                - disabled: false
                - keyByIndex:
                    array: []
                - _labels:
                    - Menu item 1
                    - Menu item 2
                    - Menu item 3
                - srcType: src
                - disabledByIndex:
                    array: []
                - horizontalAlignment: left
                - maintainSpaceWhenHidden: false
                - labels:
                    array: []
            style:
              ordered: []
            position2:
              position2:
                row: 0.40000000000000036
                height: 0.8
                width: 10
            createdAt: 2022-12-15T19:29:37.178Z
  queryStatusVisibility: false
  rootScreen: null
  version: 2.106.2
  markdownLinkBehavior: auto
